# Generated by Django 4.0 on 2022-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(default='default_cover.jpg', upload_to=''),
        ),
    ]
